### ISSUE TITLE
cannot install on Laravel 9.18

### ISSUE THREAD

**Issue by 314parley** [WyattCast44/laravel-safe-username#1]
when attempting to install in my project the following error comes through composer:

`    - wyattcast44/laravel-safe-username 3.0.0 requires illuminate/support ^7.0|^8.0 -> found illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
`

**Comment by WyattCast44** [comment]
Just released a new tag, should be able to install version ^4.0. Hope this helps
